name: Docker Build and Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta (Development)
        id: meta-development
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
            suffix=-development,onlatest=true
          tags: |
            type=raw,value=development
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Docker meta (Production)
        id: meta-production
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
          tags: |
            type=raw,value=production
            type=raw,value=latest-production
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern={{version}},suffix=-production
            type=semver,pattern={{major}}.{{minor}},suffix=-production
            type=semver,pattern={{major}},suffix=-production

      - name: Build and push (Development)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.development
          push: true
          tags: ${{ steps.meta-development.outputs.tags }}
          labels: ${{ steps.meta-development.outputs.labels }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}

      - name: Build and push (Production)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.production
          push: true
          tags: ${{ steps.meta-production.outputs.tags }}
          labels: ${{ steps.meta-production.outputs.labels }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}
